# Generated by Django 4.1.3 on 2023-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='descripcion',
            field=models.CharField(max_length=30, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mensaje',
            field=models.CharField(max_length=200, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
